#!/bin/bash

# 🏆 IDENTITY SPOOFING DETECTION SYSTEM
# Complete Hackathon Solution - Installation & Quick Start

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   🔐 Identity Spoofing Detection System - Quick Start          ║"
echo "║   Problem: Prevent identity spoofing in gated communities     ║"
echo "║   Status: READY TO DEMO ✅                                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if we're in the right directory
if [ ! -f "app.py" ]; then
    echo -e "${RED}❌ Error: Please run this from the backend/ directory${NC}"
    exit 1
fi

echo -e "${BLUE}📁 Project Structure:${NC}"
echo "identity-spoofing-detection/"
echo "├── backend/ (Flask API)"
echo "├── frontend/ (React Dashboard)"
echo "├── Dockerfile"
echo "├── docker-compose.yml"
echo "├── README.md"
echo "├── PRESENTATION.md"
echo "├── DEMO_SCRIPT.md"
echo "└── QUICKSTART.sh"
echo ""

echo -e "${BLUE}🚀 OPTION 1: Local Development (Recommended for Demo)${NC}"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Terminal 1 - Start Backend:"
echo "  $ cd backend"
echo "  $ python -m venv venv"
echo "  $ source venv/bin/activate  # Windows: venv\\Scripts\\activate"
echo "  $ pip install -r requirements.txt"
echo "  $ python app.py"
echo ""
echo "Terminal 2 - Start Frontend:"
echo "  $ cd frontend"
echo "  $ npm install"
echo "  $ npm start"
echo ""
echo "Terminal 3 - Test API:"
echo "  $ curl http://localhost:5000/api/health"
echo ""
echo -e "${GREEN}✅ Ready when you see:${NC}"
echo "   Backend: 'Server running on http://localhost:5000'"
echo "   Frontend: 'Compiled successfully!'"
echo ""

echo -e "${BLUE}🐳 OPTION 2: Docker Deployment (Production)${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  $ docker-compose up -d"
echo "  $ # Wait for ~30 seconds for containers to start"
echo "  $ docker-compose logs -f"
echo ""
echo -e "${GREEN}✅ Services running on:${NC}"
echo "   Backend: http://localhost:5000"
echo "   Frontend: http://localhost:3000"
echo "   Database: PostgreSQL on 5432"
echo ""

echo -e "${BLUE}📚 DOCUMENTATION FILES:${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  📖 README.md             - Complete system documentation"
echo "  🎬 DEMO_SCRIPT.md        - Live demo walkthrough (12 minutes)"
echo "  🎯 PRESENTATION.md       - 18-slide presentation for judges"
echo "  📋 PROJECT_SUMMARY.md    - What you've accomplished"
echo "  ⚡ QUICKSTART.sh         - 5-minute setup guide"
echo ""

echo -e "${BLUE}🔧 QUICK API TESTS:${NC}"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "1. Check System Health:"
echo "   curl http://localhost:5000/api/health"
echo ""
echo "2. Register a User:"
echo "   curl -X POST http://localhost:5000/api/auth/register-user \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"name\":\"John Doe\",\"email\":\"john@example.com\",\"phone\":\"9876543210\",\"unit\":\"A101\"}'"
echo ""
echo "3. Issue Credential:"
echo "   curl -X POST http://localhost:5000/api/auth/issue-credential/1 \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"credential_type\":\"qr_code\",\"valid_for_days\":30}'"
echo ""
echo "4. Get Dashboard Overview:"
echo "   curl http://localhost:5000/api/dashboard/overview"
echo ""
echo "5. Open Dashboard UI:"
echo "   → Open browser at http://localhost:3000"
echo ""

echo -e "${YELLOW}⏱️  TYPICAL SETUP TIME:${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  • Local Setup: 5-10 minutes"
echo "  • Docker Setup: 2-3 minutes"
echo "  • First Demo Run: 15 minutes (+ Q&A)"
echo ""

echo -e "${YELLOW}⚠️  COMMON ISSUES:${NC}"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Port 5000 already in use:"
echo "  $ lsof -i :5000  # Find process"
echo "  $ kill -9 <PID>  # Kill it"
echo ""
echo "npm install fails:"
echo "  $ npm cache clean --force"
echo "  $ rm -rf node_modules package-lock.json"
echo "  $ npm install"
echo ""
echo "DeepFace model download slow:"
echo "  ✓ First run downloads models (~300MB)"
echo "  ✓ Subsequent runs are instant"
echo "  ✓ Models cached in ~/.deepface/"
echo ""

echo -e "${BLUE}🎯 DEMO CHECKLIST:${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "Before demoing to judges:"
echo ""
echo "  ☐ Both backend and frontend running"
echo "  ☐ API health check passes"
echo "  ☐ Dashboard loads at http://localhost:3000"
echo "  ☐ Database is initialized"
echo "  ☐ Read DEMO_SCRIPT.md for talking points"
echo "  ☐ Practice the demo 2-3 times"
echo "  ☐ Prepare Q&A answers (in DEMO_SCRIPT.md)"
echo "  ☐ Have backup laptop ready"
echo "  ☐ Laptop has 50%+ battery"
echo "  ☐ Internet connection stable"
echo ""

echo -e "${GREEN}🏆 YOU'RE ALL SET!${NC}"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "What you have:"
echo "  ✅ Production-ready backend (Flask + ML/AI)"
echo "  ✅ Beautiful React dashboard"
echo "  ✅ Real-time monitoring system"
echo "  ✅ Professional presentation (18 slides)"
echo "  ✅ Complete demo script with Q&A"
echo "  ✅ Docker deployment ready"
echo "  ✅ Full documentation"
echo ""
echo "You're ready to WIN the hackathon! 🎉"
echo ""
echo "Questions? Check:"
echo "  • README.md - System documentation"
echo "  • DEMO_SCRIPT.md - Demo walkthrough"
echo "  • PRESENTATION.md - Slide content"
echo ""
echo "Good luck! 🌟"
echo ""
